RentMovies.Web/RentMovies.Web/Models/CategoryViewModel.cs
namespace RentMovies.Web.Models
{
    public class CategoryViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

RentMovies.Web/RentMovies.Web/Models/ErrorViewModel.cs
namespace RentMovies.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RentMovies.Web/RentMovies.Web/Models/MovieViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RentMovies.Web.Models
{
    public class MovieViewModel
    {
        public int Id { get; set; }
        [StringLength(60)]

        public string Title { get; set; }
        [StringLength(60)]

        public string Description { get; set; }

        public string Category { get; set; }
    }
}

RentMovies.Web/RentMovies.Web/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using RentMovies.Ifraestructure;
using RentMovies.Web.Models;

namespace RentMovies.Web
{
    public class CategoriesController : Controller
    {
        private readonly DataContext _context;

        public CategoriesController()
        {
        }



        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            return View(new CategoryViewModel { Id = id });
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        public async Task<IActionResult> Edit(int id)
        {
            return View(new CategoryViewModel { Id = id });
        }

        public async Task<IActionResult> Delete(int id)
        {
            return View(new CategoryViewModel { Id = id });
        }

    }
}

RentMovies.Web/RentMovies.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RentMovies.Web.Models;
using System.Diagnostics;

namespace RentMovies.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RentMovies.Web/RentMovies.Web/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentMovies.Domain.Entities;
using RentMovies.Ifraestructure;
using RentMovies.Web.Models;

namespace RentMovies.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly DataContext _context;

        public MoviesController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string title, string brand)
        {
            var entities = _context.Movies.Where(p => p.Id > 0);
            var filterResult = entities;
            if (!string.IsNullOrEmpty(title))
            {
                filterResult = entities.Where(v => v.Title.ToLower().Contains(title.ToLower()));
            }

            return View(await filterResult.ToListAsync());
        }



        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        public async Task<IActionResult> Create()
        {
            var movie = new MovieViewModel();

            return View(movie);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MovieViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var entity = new Movie();
                entity.Title = viewModel.Title;
                entity.Description = viewModel.Description;
                entity.Category = viewModel.Category;


                _context.Movies.Add(entity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entity = await _context.Movies.FindAsync(id);
            if (entity == null)
            {
                return NotFound();
            }
            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        private async Task<IActionResult> Edit(int id, Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExist(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }



        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entity = await _context.Movies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entity == null)
            {
                return NotFound();
            }

            return View(entity);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var entity = await _context.Movies.FindAsync(id);
            if (entity != null)
            {
                _context.Movies.Remove(entity);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
            return _context.Movies.Any(e => e.Id == id);
        }


        private bool MovieExist(int id)
        {
            return _context.Movies.Any(e => e.Id == id);
        }
    }
}

RentMovies.Web/RentMovies.Web/Views/Categories/Create.cshtml
@model CategoryViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        function saveCategory() {
            let categoryObj = {
                name: $("#Name").val()
            };

            $.ajax({
                    url: "https://localhost:7251/Categories/Add",
                type: "POST",
                contentType: "application/json",
                data: JSON.stringify(categoryObj),
                success: function (response) {
                    if (response.success) {
                        window.location.href = "/Categories/Index";
                    } else {
                        alert("Error: " + response.message);
                    }
                }
            });
        }
    </script>
}

RentMovies.Web/RentMovies.Web/Views/Categories/Delete.cshtml
@model CategoryViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RentMovies.Web/RentMovies.Web/Views/Categories/Details.cshtml
@model CategoryViewModel


@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RentMovies.Web/RentMovies.Web/Views/Categories/Edit.cshtml
@model CategoryViewModel


@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentMovies.Web/RentMovies.Web/Views/Categories/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<h1>Index</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>
<div class="row mb-3">
    <div class="col-md-4">
        <input id="search" class="form-control" placeholder="Search..." onkeyup="loadCategories()" />
    </div>
</div>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Name
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody id="categoriesTable">
    </tbody>
</table>

@section Scripts {
    <script>

        $(document).ready(function () {
            loadCategories();
        });

        function loadCategories() {
            let filter = $("#search").val();

                    $.get("https://localhost:7028/Movies/GetAll", { filter: filter }, function (data) {
                let rows = "";
                console.log(data);
                data.forEach(item => {
                    rows += `<tr>
                        <td>${item.name}</td>
                        <td>
                                <a href="/Categories/Details/${item.id}" class="btn btn-info btn-sm">Details</a>
                                <a href="/Categories/Edit/${item.id}" class="btn btn-warning btn-sm">Edit</a>
                                <a href="/Categories/Delete/${item.id}" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>`;
                });
                $("#categoriesTable").html(rows);
            });
        }
    </script>

}

RentMovies.Web/RentMovies.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RentMovies.Web/RentMovies.Web/Views/Movies/Create.cshtml
@model RentMovies.Web.Models.MovieViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        function saveMovie() {
            let MovieObj = {
                title: $("#Title").val(),
                description: $("#Description").val(),
                category: $("#Category").val()
            };

            $.ajax({
                    url: "https://localhost:7251/Movie/Add",
                type: "POST",
                contentType: "application/json",
                data: JSON.stringify(categoryObj),
                success: function (response) {
                    if (response.success) {
                        window.location.href = "/Movies/Index";
                    } else {
                        alert("Error: " + response.message);
                    }
                }
            });
        }
    </script>
}

RentMovies.Web/RentMovies.Web/Views/Movies/Delete.cshtml
@model Movie

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RentMovies.Web/RentMovies.Web/Views/Movies/Details.cshtml
@model Movie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RentMovies.Web/RentMovies.Web/Views/Movies/Edit.cshtml
@model Movie

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentMovies.Web/RentMovies.Web/Views/Movies/Index.cshtml
@model IEnumerable<Movie>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a class="btn-outline-primary btn" asp-action="Create">Insert new Movie</a>
</p>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                    <a class="btn-outline-success btn" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a class="btn-outline-info btn" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a class="btn-outline-danger btn" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RentMovies.Web/RentMovies.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentMovies.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RentMovies.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RentMovies.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - RentMovies.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>